# Generated by Django 4.1.5 on 2023-01-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='graduation_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='program_of_study',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
