# Generated by Django 4.1.5 on 2023-01-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewBlog', '0002_users_graduation_year_users_program_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='select_degree',
        ),
    ]
